import { MapContainer, TileLayer, ScaleControl, Marker, Popup, Circle, useMap, useMapEvents } from 'react-leaflet'
import 'leaflet/dist/leaflet.css'
import L from 'leaflet'
import markerIcon2x from 'leaflet/dist/images/marker-icon-2x.png'
import markerIcon from 'leaflet/dist/images/marker-icon.png'
import markerShadow from 'leaflet/dist/images/marker-shadow.png'
import { useState, useEffect } from 'react'
import LayerControls from './components/LayerControls'
import Search from './components/Search'
import AssetCard from './components/AssetCard'
import IncidentMode from './components/IncidentMode'
import useStore, { type Asset } from './store'
import { markerIconFor } from './markerIcons'

// Fix default marker icons not loading under bundlers (Vite)
L.Icon.Default.mergeOptions({
  iconRetinaUrl: markerIcon2x,
  iconUrl: markerIcon,
  shadowUrl: markerShadow,
})

// Default view for South East Wales
const DEFAULT_CENTER = { lat: 51.5, lng: -3.2 }
const DEFAULT_ZOOM = 10

// Reacts to store center/zoom changes and moves the map (used by Search)
function MapController() {
  const map = useMap()
  const { center, zoom } = useStore()

  useEffect(() => {
    map.setView([center.lat, center.lng], zoom)
  }, [map, center, zoom])

  return null
}

// Handles map clicks to drop an incident pin
function MapClickHandler({ enabled }: { enabled: boolean }) {
  const { setIncidentLocation } = useStore()

  useMapEvents({
    click(e) {
      if (enabled) {
        setIncidentLocation(e.latlng.lat, e.latlng.lng)
      }
    },
  })

  return null
}

interface MapLayersProps {
  onAssetClick: (asset: Asset) => void
  incidentModeEnabled: boolean
}

function MapLayers({ onAssetClick, incidentModeEnabled }: MapLayersProps) {
  const { assets, activeCategories, incidentLocation } = useStore()

  // Filter assets by active categories
  const filteredAssets = assets.filter((asset) =>
    activeCategories.includes(asset.category)
  )

  return (
    <>
      <TileLayer
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        attribution="&copy; OpenStreetMap contributors"
      />
      <ScaleControl position="bottomleft" />
      <MapController />
      <MapClickHandler enabled={incidentModeEnabled} />

      {/* Incident location marker + radius rings */}
      {incidentLocation && (
        <>
          <Marker position={[incidentLocation.lat, incidentLocation.lng]}>
            <Popup>
              <strong>Incident Location</strong>
              <br />
              {incidentLocation.lat.toFixed(4)}, {incidentLocation.lng.toFixed(4)}
            </Popup>
          </Marker>
          {[5, 10, 20].map((miles) => (
            <Circle
              key={miles}
              center={[incidentLocation.lat, incidentLocation.lng]}
              radius={miles * 1609.34}
              pathOptions={{ color: '#dc2626', weight: 1, fillOpacity: 0.03 }}
            />
          ))}
        </>
      )}

      {/* Asset markers */}
      {filteredAssets.map((asset) => (
        <Marker
          key={asset.id}
          position={[asset.latitude, asset.longitude]}
          icon={markerIconFor(asset.category)}
        >
          <Popup>
            <div className="min-w-[180px]">
              <div className="font-semibold text-sm mb-1">{asset.name}</div>
              <div className="text-xs text-gray-500 mb-1 capitalize">
                {asset.category.replace(/_/g, ' ')}
              </div>
              {asset.address && (
                <div className="text-xs mb-1">{asset.address}</div>
              )}
              {asset.phone && (
                <div className="text-xs mb-1">
                  <a href={`tel:${asset.phone}`} className="text-blue-600">
                    {asset.phone}
                  </a>
                </div>
              )}
              {asset.openingHours && (
                <div className="text-xs mb-1 text-gray-600">{asset.openingHours}</div>
              )}
              <button
                onClick={() => onAssetClick(asset)}
                className="text-blue-600 hover:underline text-xs font-semibold mt-1"
              >
                More details →
              </button>
            </div>
          </Popup>
        </Marker>
      ))}
    </>
  )
}

function App() {
  const [showIncidentMode, setShowIncidentMode] = useState(false)
  const [selectedAsset, setSelectedAsset] = useState<Asset | null>(null)
  const { setAssets, setCategories, incidentLocation } = useStore()

  // Load gazetteer data (generated by the Overpass pipeline) on mount
  useEffect(() => {
    async function loadAssets() {
      try {
        const response = await fetch(`${import.meta.env.BASE_URL}data/gazetteer.json`)
        if (!response.ok) {
          throw new Error(`Failed to load gazetteer: ${response.status}`)
        }
        const data: Asset[] = await response.json()
        setAssets(data)
      } catch (error) {
        console.error('Error loading gazetteer data:', error)
        setAssets([])
      }
    }

    loadAssets()
    setCategories([
      'hospital',
      'community_hospital',
      'fire_station',
      'police_station',
      'ambulance_station',
      'mountain_rescue',
      'fuel_station',
    ])
  }, [setAssets, setCategories])

  return (
    <div className="flex flex-col h-screen">
      <header className="bg-blue-900 text-white px-3 py-2 shadow-md z-[1100] relative">
        <div className="flex items-center justify-between gap-2">
          <div className="min-w-0">
            <h1 className="text-lg sm:text-2xl font-bold leading-tight truncate">
              Responder Gazetteer
            </h1>
            <p className="text-xs text-blue-200 hidden sm:block">
              Operational awareness tool for 4x4 Response Wales
            </p>
          </div>
          <button
            onClick={() => setShowIncidentMode(!showIncidentMode)}
            className="flex-shrink-0 bg-red-600 text-white px-3 py-2 rounded-lg shadow active:bg-red-700 font-semibold text-sm whitespace-nowrap"
          >
            {showIncidentMode ? 'Close' : 'Incident'}
          </button>
        </div>
        {/* Full-width search bar under the title - never collides with map controls */}
        <div className="mt-2">
          <Search />
        </div>
      </header>

      <main className="flex-1 relative">
        {/* Map */}
        <MapContainer
          center={[DEFAULT_CENTER.lat, DEFAULT_CENTER.lng]}
          zoom={DEFAULT_ZOOM}
          style={{ height: '100%', width: '100%' }}
          zoomControl={false}
        >
          <MapLayers
            onAssetClick={setSelectedAsset}
            incidentModeEnabled={showIncidentMode}
          />
        </MapContainer>

        {/* Layer controls float top-right, collapsed to a button by default */}
        <LayerControls />

        {showIncidentMode && <IncidentMode onClose={() => setShowIncidentMode(false)} />}

        {selectedAsset && (
          <div className="absolute inset-x-0 bottom-0 z-[1000] sm:inset-x-auto sm:top-4 sm:right-4 sm:bottom-auto sm:w-96">
            <AssetCard
              asset={selectedAsset}
              incidentLat={incidentLocation?.lat ?? null}
              incidentLng={incidentLocation?.lng ?? null}
              onClose={() => setSelectedAsset(null)}
            />
          </div>
        )}
      </main>
    </div>
  )
}

export default App
